name: Linux Build with Premake 5

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Generate Project for gmake2
      run: ./vendor/bin/premake5 gmake2
    - name: Build - Release
      run: make config=release
    - name: Run - Release
      run: ./bin/Release/BasicApp