name: Linux Build with Premake 5

on: [push]

jobs:
  linux-clang:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Grant premake5 permission
      run: chmod 777 ./vendor/bin/premake5
    - name: Generate Project for gmake2
      run: ./vendor/bin/premake5 --cc=clang gmake2
    - name: Build - Debug
      run: make config=debug
    - name: Run - Debug
      run: ./bin/Debug/BasicApp
    - name: Build - Release
      run: make config=release
    - name: Run - Release
      run: ./bin/Release/BasicApp